flags:
  text:
    integer-simple: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- MonadRandom-0.4
- QuickCheck-2.8.1
- StateVar-1.1.0.1
- aeson-0.10.0.0
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.0.2
- attoparsec-0.13.0.1
- auto-update-0.1.2.2
- base-orphans-0.4.4
- bifunctors-5
- blaze-builder-0.4.0.1
- bytestring-builder-0.10.6.0.0
- case-insensitive-1.2.0.5
- clock-0.5.1
- comonad-4.2.7.2
- conduit-1.2.5.1
- conduit-extra-1.1.9.1
- contravariant-1.3.3
- cpphs-1.19.3
- data-default-0.5.3
- data-default-class-0.0.1
- data-default-instances-base-0.0.1
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- distributive-0.4.4
- dlist-0.7.1.2
- either-4.4.1
- exceptions-0.8.0.2
- fast-logger-2.4.1
- file-embed-0.0.9
- free-4.12.1
- hashable-1.2.3.3
- haskell-src-exts-1.16.0.1
- haskell-src-meta-0.6.0.11
- hreader-1.0.1
- hset-2.1.0
- ieee754-0.7.6
- inflections-0.2.0.0
- language-haskell-extract-0.2.4
- lifted-base-0.2.3.6
- mmorph-1.0.4
- monad-control-1.0.0.4
- monad-logger-0.3.15
- monad-loops-0.4.3
- mtl-2.2.1
- nats-1
- network-2.6.2.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.12.0.0
- parsec-3.1.9
- polyparse-1.11
- postgresql-libpq-0.9.1.1
- postgresql-simple-0.5.1.0
- prelude-extras-0.4.0.2
- primitive-0.6.1.0
- profunctors-5.1.1
- quickcheck-assertions-0.2.0
- quickcheck-instances-0.3.11
- random-1.1
- regex-base-0.93.2
- regex-posix-0.95.2
- regex-tdfa-rc-1.1.8.3
- resource-pool-0.2.3.2
- resourcet-1.1.6
- safe-0.3.9
- scientific-0.3.4.2
- semigroupoids-5.0.0.4
- semigroups-0.17.0.1
- stm-2.4.4
- stm-chans-3.0.0.4
- streaming-commons-0.1.14.2
- syb-0.6
- tagged-0.8.1
- tasty-0.11.0.1
- tasty-hunit-0.9.2
- tasty-quickcheck-0.8.4
- tasty-th-0.1.3
- text-1.2.1.3
- tf-random-0.5
- th-expand-syns-0.3.0.6
- th-lift-0.7.2
- th-lift-instances-0.1.6
- th-orphans-0.12.2
- th-reify-many-0.1.3
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unbounded-delays-0.1.0.9
- unordered-containers-0.2.5.1
- uuid-types-1.0.2
- vector-0.11.0.0
- void-0.7.1
- zlib-0.6.1.1
resolver: ghc-7.10.2
